# Generated by Django 2.1.7 on 2019-08-25 16:55

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20180725_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(max_length=200, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=gallery.models.UploadImage('content'), verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.IntegerField(verbose_name='Значение'),
        ),
    ]
